### ISSUE TITLE
Display issues with long album names

### ISSUE THREAD

**Issue by charismental** [charismental/charismental.github.io#3]
Not as big of a deal with album art in separate div from player.

- Need to set up Vue filter to reduce max length to ~40 characters (if shortened, I'll add ellipsis )

**Comment by lordchuffnel** [comment]
installed npm package-   var VueTruncate = require('vue-truncate-filter')
Vue.use(VueTruncate), which created a package.json file.

so... to be redundant, added it as a <script> tag in the <head>

**Comment by lordchuffnel** [comment]
https://github.com/imcvampire/vue-truncate-filter/blob/master/package.json

**Comment by charismental** [comment]
Eventually I will rebuild this as a vue component, good find on the filter, I might simplify it though by creating a Vue.filter, then changing markup to {{ song.album | truncateFilter }}
